"""Out-of-time calibration for the Kalman ARIMA+ANN hybrid predictor.

This module intentionally does not modify :mod:`kf_enbpi`.  The predictor is
still a bootstrap ensemble of ARIMA and ANN models, but its conformal residuals
are generated by expanding-window block cross-fitting:

1. fit the complete hybrid on observations strictly before a validation block;
2. make causal one-step forecasts throughout that future block;
3. refit at the next block boundary;
4. select a trailing residual-window length using training residuals only;
5. fit the final hybrid on all training observations and update the selected
   residual window sequentially after each test response is revealed.

The interval remains the original EnbPI shortest residual interval.  This is
not an equal-tail conformal interval.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from time import perf_counter

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from .kf_enbpi import (
    Array,
    EnbPIConfig,
    EnbPIResult,
    KalmanEnbPI,
    ModelName,
    causal_kalman_decomposition,
    make_lagged_features,
    shortest_residual_offsets,
    simulate_additive_data,
)


@dataclass(frozen=True)
class OutOfTimeEnbPIConfig:
    """Settings added on top of the existing hybrid predictor configuration."""

    base: EnbPIConfig = field(default_factory=EnbPIConfig)
    # The prefix before the first validation block.  It is never scored as
    # calibration data because no earlier model is available for it.
    initial_train_fraction: float = 0.50
    n_crossfit_blocks: int = 4
    # None means all currently available calibration residuals.
    residual_window_candidates: tuple[int | None, ...] = (
        100,
        200,
        300,
        400,
        None,
    )
    # The latest part of the out-of-time residual sequence is used to compare W.
    window_validation_fraction: float = 0.40
    min_window_history: int = 40


@dataclass
class OutOfTimeEnbPIResult:
    """Forecast plus the audit trail for cross-fitting and window selection."""

    forecast: EnbPIResult
    crossfit_predictions: pd.DataFrame
    fold_summary: pd.DataFrame
    window_selection: pd.DataFrame
    selected_residual_window: int | None
    initial_pool_size: int

    def metrics(self) -> dict[str, float | str]:
        metrics: dict[str, float | str] = dict(self.forecast.metrics())
        fold_retries = float(
            self.fold_summary.get("arima_retry_count", pd.Series(dtype=float)).sum()
        )
        fold_failures = float(
            self.fold_summary.get(
                "arima_nonconverged_fits", pd.Series(dtype=float)
            ).sum()
        )
        metrics.update(
            {
                "calibration_method": "rolling_origin_block_crossfit",
                "selected_residual_window": (
                    "all"
                    if self.selected_residual_window is None
                    else float(self.selected_residual_window)
                ),
                "crossfit_residual_count": float(len(self.crossfit_predictions)),
                "crossfit_fold_count": float(len(self.fold_summary)),
                "initial_test_pool_size": float(self.initial_pool_size),
                # Include both temporary cross-fit engines and the final engine.
                "arima_retry_count": (
                    float(self.forecast.arima_retry_count) + fold_retries
                ),
                "arima_nonconverged_fits": (
                    float(self.forecast.arima_nonconverged_fits) + fold_failures
                ),
            }
        )
        return metrics

    def summary_tables(self) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        final, components = self.forecast.summary_tables()
        metrics = self.metrics()
        final["arima_retry_count"] = int(metrics["arima_retry_count"])
        final["arima_nonconverged_fits"] = int(
            metrics["arima_nonconverged_fits"]
        )
        calibration = pd.DataFrame([metrics])[
            [
                "calibration_method",
                "selected_residual_window",
                "crossfit_residual_count",
                "crossfit_fold_count",
                "initial_test_pool_size",
                "arima_retry_count",
                "arima_nonconverged_fits",
            ]
        ]
        return final, components, calibration


def _validate_config(config: OutOfTimeEnbPIConfig, train_size: int) -> int:
    base = config.base
    if base.batch_size != 1:
        raise ValueError(
            "Out-of-time calibration requires batch_size=1 so every test "
            "residual is revealed before the next forecast."
        )
    if not 0.0 < config.initial_train_fraction < 1.0:
        raise ValueError("initial_train_fraction must lie in (0, 1)")
    if config.n_crossfit_blocks < 2:
        raise ValueError("n_crossfit_blocks must be at least 2")
    if not 0.0 < config.window_validation_fraction < 1.0:
        raise ValueError("window_validation_fraction must lie in (0, 1)")
    if config.min_window_history < 2:
        raise ValueError("min_window_history must be at least 2")
    if not config.residual_window_candidates:
        raise ValueError("residual_window_candidates must not be empty")
    for candidate in config.residual_window_candidates:
        if candidate is not None and candidate < 2:
            raise ValueError("Every finite residual-window candidate must be >= 2")

    initial_size = int(round(train_size * config.initial_train_fraction))
    initial_size = max(initial_size, base.window_size + 8)
    if initial_size >= train_size - config.n_crossfit_blocks:
        raise ValueError(
            "The initial prefix leaves too few observations for cross-fit blocks"
        )
    return initial_size


def _fit_hybrid(
    observed_prefix: Array,
    config: EnbPIConfig,
    *,
    fold_seed: int,
) -> tuple[KalmanEnbPI, Array, Array]:
    """Fit both branches using only one chronological prefix."""
    prefix = np.asarray(observed_prefix, dtype=float)
    low, high = causal_kalman_decomposition(
        prefix,
        process_variance=config.process_variance,
        measurement_variance=config.measurement_variance,
    )
    x_train, y_train, target_times = make_lagged_features(
        prefix, low, high, config.window_size
    )
    fold_config = replace(config, random_state=int(fold_seed))
    engine = KalmanEnbPI(fold_config).fit(
        x_train, y_train, low, high, target_times
    )
    return engine, low, high


def _mean_hybrid_forecast(
    engine: KalmanEnbPI,
    history: Array,
    config: EnbPIConfig,
) -> tuple[float, float, float]:
    """Mean-aggregate the B bootstrap predictors at the next time point."""
    observed_history = np.asarray(history, dtype=float)
    low_history, high_history = causal_kalman_decomposition(
        observed_history,
        process_variance=config.process_variance,
        measurement_variance=config.measurement_variance,
    )
    x_t = np.r_[
        low_history[-config.window_size :],
        high_history[-config.window_size :],
        observed_history[-config.window_size :],
    ]
    low_base, high_base = engine.predict_base_components(low_history, x_t)
    low_center = float(np.mean(low_base))
    high_center = float(np.mean(high_base))
    return low_center + high_center, low_center, high_center


def rolling_origin_crossfit(
    observed_train: Array,
    config: OutOfTimeEnbPIConfig,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Generate honest future-block residuals inside the training period.

    Model and hyperparameter selection at fold ``k`` only see observations with
    index smaller than that fold's first validation time.
    """
    y = np.asarray(observed_train, dtype=float)
    if y.ndim != 1:
        raise ValueError("observed_train must be one-dimensional")
    initial_size = _validate_config(config, len(y))
    blocks = [
        block
        for block in np.array_split(
            np.arange(initial_size, len(y), dtype=int),
            config.n_crossfit_blocks,
        )
        if len(block)
    ]
    reference_low, reference_high = causal_kalman_decomposition(
        y,
        process_variance=config.base.process_variance,
        measurement_variance=config.base.measurement_variance,
    )
    seed_sequence = np.random.SeedSequence(config.base.random_state)
    fold_seeds = seed_sequence.spawn(len(blocks))
    rows: list[dict[str, float | int | str]] = []
    fold_rows: list[dict[str, float | int | str]] = []

    for fold_number, (block, seed) in enumerate(
        zip(blocks, fold_seeds), start=1
    ):
        block_start = int(block[0])
        block_stop = int(block[-1]) + 1
        fold_seed = int(seed.generate_state(1)[0])
        engine, _, _ = _fit_hybrid(
            y[:block_start], config.base, fold_seed=fold_seed
        )

        for t in block:
            # y[:t] contains every response revealed before t and never y[t].
            final_center, low_center, high_center = _mean_hybrid_forecast(
                engine, y[:t], config.base
            )
            rows.append(
                {
                    "fold": fold_number,
                    "fit_end_exclusive": block_start,
                    "time": int(t),
                    "truth": float(y[t]),
                    "final_point": final_center,
                    "low_reference": float(reference_low[t]),
                    "low_point": low_center,
                    "high_reference": float(reference_high[t]),
                    "high_point": high_center,
                    "final_residual": float(y[t] - final_center),
                    "low_residual": float(reference_low[t] - low_center),
                    "high_residual": float(reference_high[t] - high_center),
                }
            )

        fold_rows.append(
            {
                "fold": fold_number,
                "train_start": 0,
                "train_stop_exclusive": block_start,
                "validation_start": block_start,
                "validation_stop_exclusive": block_stop,
                "n_train_observations": block_start,
                "n_validation_observations": len(block),
                "arima_order": str(engine.selected_arima_order),
                "ann_selected_max_iter_mean": float(
                    np.mean(engine.selected_ann_max_iters)
                ),
                "arima_retry_count": engine.arima_retry_count,
                "arima_nonconverged_fits": engine.arima_nonconverged_fits,
                "random_state": fold_seed,
            }
        )

    predictions = pd.DataFrame(rows)
    folds = pd.DataFrame(fold_rows)
    if predictions.empty:
        raise RuntimeError("No cross-fit predictions were generated")
    if not np.all(
        predictions["fit_end_exclusive"].to_numpy()
        <= predictions["time"].to_numpy()
    ):
        raise RuntimeError("Cross-fit audit failed: a fit crossed validation time")
    identity_error = (
        predictions["final_residual"]
        - predictions["low_residual"]
        - predictions["high_residual"]
    )
    if not np.allclose(identity_error, 0.0, atol=1e-10):
        raise RuntimeError("Combined residual is not the sum of component residuals")
    return predictions, folds


def interval_score(
    truth: float,
    lower: float,
    upper: float,
    alpha: float,
) -> float:
    """Gneiting--Raftery interval score; smaller is better."""
    score = upper - lower
    if truth < lower:
        score += (2.0 / alpha) * (lower - truth)
    elif truth > upper:
        score += (2.0 / alpha) * (truth - upper)
    return float(score)


def _window_label(window: int | None) -> str:
    return "all" if window is None else str(int(window))


def select_residual_window(
    residuals: Array,
    config: OutOfTimeEnbPIConfig,
) -> tuple[int | None, pd.DataFrame]:
    """Choose W by prequential interval score on training residuals only."""
    values = np.asarray(residuals, dtype=float)
    values = values[np.isfinite(values)]
    n = len(values)
    validation_start = max(
        config.min_window_history,
        int(np.floor(n * (1.0 - config.window_validation_fraction))),
    )
    if validation_start >= n:
        raise ValueError(
            "Not enough cross-fit residuals for adaptive-window validation"
        )

    rows: list[dict[str, float | int | str]] = []
    for candidate in config.residual_window_candidates:
        scores: list[float] = []
        covered: list[bool] = []
        widths: list[float] = []
        for j in range(validation_start, n):
            history = values[:j]
            if candidate is not None:
                history = history[-candidate:]
            bias = (
                float(np.mean(history))
                if config.base.oob_bias_correction
                else 0.0
            )
            lower_offset, upper_offset, _ = shortest_residual_offsets(
                history - bias,
                config.base.alpha,
                config.base.beta_grid_size,
            )
            lower = bias + lower_offset
            upper = bias + upper_offset
            scores.append(
                interval_score(values[j], lower, upper, config.base.alpha)
            )
            covered.append(lower <= values[j] <= upper)
            widths.append(upper - lower)

        rows.append(
            {
                "window": _window_label(candidate),
                "window_value": np.nan if candidate is None else int(candidate),
                "mean_interval_score": float(np.mean(scores)),
                "coverage": float(np.mean(covered)),
                "mean_width": float(np.mean(widths)),
                "n_validation_residuals": len(scores),
                "validation_start_position": validation_start,
            }
        )

    selection = pd.DataFrame(rows).sort_values(
        ["mean_interval_score", "mean_width"],
        kind="stable",
    ).reset_index(drop=True)
    best_label = str(selection.iloc[0]["window"])
    selected = None if best_label == "all" else int(best_label)
    selection["selected"] = selection["window"] == best_label
    return selected, selection


def _restrict_pool(values: Array, window: int | None) -> Array:
    pool = np.asarray(values, dtype=float)
    if window is None:
        return np.array(pool, copy=True)
    return np.array(pool[-window:], copy=True)


def _update_pool(pool: Array, residual: float, max_size: int) -> Array:
    updated = np.r_[np.asarray(pool, dtype=float), float(residual)]
    return updated[-max_size:]


def run_out_of_time_enbpi(
    observed: Array,
    train_size: int,
    *,
    config: OutOfTimeEnbPIConfig,
    model_name: str = "custom",
    true_low: Array | None = None,
    true_high: Array | None = None,
    data_seed: int | None = None,
) -> OutOfTimeEnbPIResult:
    """Run joint out-of-time calibration and sequential adaptive-window EnbPI."""
    started = perf_counter()
    y = np.asarray(observed, dtype=float)
    if y.ndim != 1 or not config.base.window_size < train_size < len(y):
        raise ValueError("Need window_size < train_size < len(observed)")
    _validate_config(config, train_size)

    crossfit, fold_summary = rolling_origin_crossfit(y[:train_size], config)
    selected_window, window_selection = select_residual_window(
        crossfit["final_residual"].to_numpy(), config
    )
    residual_pool = _restrict_pool(
        crossfit["final_residual"].to_numpy(), selected_window
    )
    low_residual_pool = _restrict_pool(
        crossfit["low_residual"].to_numpy(), selected_window
    )
    high_residual_pool = _restrict_pool(
        crossfit["high_residual"].to_numpy(), selected_window
    )
    initial_residual_pool = np.array(residual_pool, copy=True)
    initial_low_residual_pool = np.array(low_residual_pool, copy=True)
    initial_high_residual_pool = np.array(high_residual_pool, copy=True)
    max_pool_size = len(residual_pool)

    final_engine, _, _ = _fit_hybrid(
        y[:train_size],
        config.base,
        fold_seed=config.base.random_state,
    )
    estimated_low, estimated_high = causal_kalman_decomposition(
        y,
        process_variance=config.base.process_variance,
        measurement_variance=config.base.measurement_variance,
    )
    test_times = np.arange(train_size, len(y), dtype=int)
    truth = y[test_times]
    n_test = len(test_times)
    point = np.empty(n_test)
    lower = np.empty(n_test)
    upper = np.empty(n_test)
    low_point = np.empty(n_test)
    low_lower = np.empty(n_test)
    low_upper = np.empty(n_test)
    high_point = np.empty(n_test)
    high_lower = np.empty(n_test)
    high_upper = np.empty(n_test)
    beta = np.empty(n_test)
    low_beta = np.empty(n_test)
    high_beta = np.empty(n_test)
    bias_correction = np.empty(n_test)
    low_bias_correction = np.empty(n_test)
    high_bias_correction = np.empty(n_test)

    for j, t in enumerate(test_times):
        mode = config.base.oob_bias_correction_mode
        if mode not in ("component", "combined"):
            raise ValueError(
                "oob_bias_correction_mode must be 'component' or 'combined'"
            )
        if not config.base.oob_bias_correction:
            low_bias = high_bias = final_bias = 0.0
        elif mode == "component":
            low_bias = float(np.mean(low_residual_pool))
            high_bias = float(np.mean(high_residual_pool))
            final_bias = low_bias + high_bias
        else:
            low_bias = high_bias = 0.0
            final_bias = float(np.mean(residual_pool))

        final_lo, final_hi, beta[j] = shortest_residual_offsets(
            residual_pool - final_bias,
            config.base.alpha,
            config.base.beta_grid_size,
        )
        low_lo, low_hi, low_beta[j] = shortest_residual_offsets(
            low_residual_pool - low_bias,
            config.base.alpha,
            config.base.beta_grid_size,
        )
        high_lo, high_hi, high_beta[j] = shortest_residual_offsets(
            high_residual_pool - high_bias,
            config.base.alpha,
            config.base.beta_grid_size,
        )
        raw_final, raw_low, raw_high = _mean_hybrid_forecast(
            final_engine, y[:t], config.base
        )

        point[j] = raw_final + final_bias
        low_point[j] = raw_low + low_bias
        high_point[j] = raw_high + high_bias
        lower[j] = point[j] + final_lo
        upper[j] = point[j] + final_hi
        low_lower[j] = low_point[j] + low_lo
        low_upper[j] = low_point[j] + low_hi
        high_lower[j] = high_point[j] + high_lo
        high_upper[j] = high_point[j] + high_hi
        bias_correction[j] = final_bias
        low_bias_correction[j] = low_bias
        high_bias_correction[j] = high_bias

        # The response and causal KF components become available only now.
        residual_pool = _update_pool(
            residual_pool, y[t] - raw_final, max_pool_size
        )
        low_residual_pool = _update_pool(
            low_residual_pool,
            estimated_low[t] - raw_low,
            max_pool_size,
        )
        high_residual_pool = _update_pool(
            high_residual_pool,
            estimated_high[t] - raw_high,
            max_pool_size,
        )

    forecast = EnbPIResult(
        model_name=model_name,
        config=config.base,
        train_size=train_size,
        test_times=test_times,
        truth=truth,
        point=point,
        lower=lower,
        upper=upper,
        low_point=low_point,
        low_lower=low_lower,
        low_upper=low_upper,
        high_point=high_point,
        high_lower=high_lower,
        high_upper=high_upper,
        beta=beta,
        low_beta=low_beta,
        high_beta=high_beta,
        bias_correction=bias_correction,
        low_bias_correction=low_bias_correction,
        high_bias_correction=high_bias_correction,
        initial_oob_residuals=initial_residual_pool,
        initial_low_oob_residuals=initial_low_residual_pool,
        initial_high_oob_residuals=initial_high_residual_pool,
        # Each cross-fit prediction is generated by all B models trained before
        # its future block; this field is retained for EnbPIResult compatibility.
        oob_counts=np.full(
            len(initial_residual_pool),
            config.base.n_bootstrap,
            dtype=int,
        ),
        estimated_low=estimated_low,
        estimated_high=estimated_high,
        observed=np.array(y, copy=True),
        true_low=None if true_low is None else np.asarray(true_low),
        true_high=None if true_high is None else np.asarray(true_high),
        data_seed=data_seed,
        selected_arima_order=final_engine.selected_arima_order,
        selected_ann_max_iters=np.asarray(
            final_engine.selected_ann_max_iters, dtype=int
        ),
        ann_rolling_validation_mse=np.asarray(
            final_engine.ann_rolling_validation_scores, dtype=float
        ),
        ann_nonconverged_models=final_engine.ann_nonconverged_models,
        elapsed_seconds=perf_counter() - started,
        arima_retry_count=final_engine.arima_retry_count,
        arima_nonconverged_fits=final_engine.arima_nonconverged_fits,
    )
    return OutOfTimeEnbPIResult(
        forecast=forecast,
        crossfit_predictions=crossfit,
        fold_summary=fold_summary,
        window_selection=window_selection,
        selected_residual_window=selected_window,
        initial_pool_size=max_pool_size,
    )


def simulate_and_run_out_of_time(
    model: ModelName,
    *,
    train_size: int = 650,
    horizon: int = 50,
    config: OutOfTimeEnbPIConfig | None = None,
    data_seed: int = 2026,
) -> OutOfTimeEnbPIResult:
    config = config or OutOfTimeEnbPIConfig()
    rng = np.random.default_rng(data_seed)
    low, high, observed = simulate_additive_data(
        model, train_size + horizon, rng=rng
    )
    return run_out_of_time_enbpi(
        observed,
        train_size,
        config=config,
        model_name=model.upper(),
        true_low=low,
        true_high=high,
        data_seed=data_seed,
    )


def monte_carlo_out_of_time(
    model: ModelName,
    *,
    n_runs: int = 20,
    train_size: int = 650,
    horizon: int = 50,
    config: OutOfTimeEnbPIConfig | None = None,
    seed: int = 2026,
) -> tuple[pd.DataFrame, pd.DataFrame, list[OutOfTimeEnbPIResult]]:
    """Monte Carlo wrapper.  Cross-fitting makes this slower than old EnbPI."""
    config = config or OutOfTimeEnbPIConfig()
    rows: list[dict[str, float | int | str]] = []
    results: list[OutOfTimeEnbPIResult] = []
    for run, child in enumerate(
        np.random.SeedSequence(seed).spawn(n_runs), start=1
    ):
        data_seed = int(child.generate_state(1)[0])
        result = simulate_and_run_out_of_time(
            model,
            train_size=train_size,
            horizon=horizon,
            config=config,
            data_seed=data_seed,
        )
        results.append(result)
        rows.append({"run": run, "data_seed": data_seed, **result.metrics()})
    runs = pd.DataFrame(rows)
    numeric = runs.select_dtypes(include=[np.number]).columns.difference(
        ["run", "data_seed"]
    )
    summary = (
        runs[numeric]
        .agg(["mean", "std"])
        .T.reset_index(names="metric")
    )
    return runs, summary, results


def plot_window_selection(
    result: OutOfTimeEnbPIResult,
) -> tuple[plt.Figure, Array]:
    """Plot training-only score, coverage, and width for candidate W values."""
    table = result.window_selection.sort_values(
        "window_value", na_position="last"
    )
    labels = table["window"].astype(str).tolist()
    x = np.arange(len(table))
    fig, axes = plt.subplots(1, 3, figsize=(14, 4))
    axes[0].plot(x, table["mean_interval_score"], marker="o")
    axes[0].set_title("Training prequential interval score")
    axes[0].set_ylabel("Lower is better")
    axes[1].plot(x, 100.0 * table["coverage"], marker="o")
    axes[1].axhline(
        100.0 * (1.0 - result.forecast.config.alpha),
        color="red",
        linestyle="--",
        label="Target",
    )
    axes[1].set_title("Training prequential coverage")
    axes[1].set_ylabel("Coverage (%)")
    axes[1].legend()
    axes[2].plot(x, table["mean_width"], marker="o")
    axes[2].set_title("Training prequential mean width")
    for axis in axes:
        axis.set_xticks(x, labels)
        axis.set_xlabel("Residual window W (all = no truncation)")
        axis.grid(alpha=0.25)
    fig.suptitle(
        "Adaptive residual-window selection "
        f"(selected W={_window_label(result.selected_residual_window)})"
    )
    fig.tight_layout()
    return fig, axes
